name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests

    - name: Build Docker image
      run: |
        docker build -t self-checkout-pipeline .

    - name: Push Docker image to GitHub Packages
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker tag self-checkout-pipeline ghcr.io/${{ github.repository }}/self-checkout-pipeline:latest
        docker push ghcr.io/${{ github.repository }}/self-checkout-pipeline:latest

    - name: Take screenshot of results
      run: |
        sudo apt-get install scrot
        scrot results.png
        git add results.png
        git commit -m "Add results screenshot"
        git push origin main
